exclude: "experiment_scheduler/master/grpc_master|experiment_scheduler/task_manager/grpc_task_manager|experiment_scheduler/resource_monitor"

repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: isort(python)

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length, "120"]

  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        name: "flake8"
        args: ["--max-line-length", "120", "--max-complexity", "20"]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/pylint
    rev: "v2.17.0"
    hooks:
      - id: pylint
        name: "pylint"
        entry: pylint
        language: system
        types: [python]
        exclude: ^experiment_scheduler/master/grpc_master/|^experiment_scheduler/task_manager/grpc_task_manager/
        args:
          - --max-line-length=120
          - --rcfile=.pylintrc

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
